In [1]:
#We follow four steps
#Data Loading --> Data Preprocessing and Visualization --> Train Test Split --> Logistic Regression Model
#Import Dependencies

In [98]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [61]:
#Load the dataset 
heartds=pd.read_csv('~/Desktop/Datasets/heart.csv')

In [62]:
#complete dataset is loaded
heartds

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   51    1   0       144   264    0        1      141      1      3.4   
303   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     1       1  
303      1   1     2       0  

[304 rows x 14 columns]

In [63]:
# target is 0 ---> Healthy Heart, safe no heart disease
# target is 1 ---> Defective Heart, means you heart disease 

In [64]:
#printing first five rows
heartds.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [65]:
#let's check the last five rows also
heartds.tail()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   51    1   0       144   264    0        1      141      1      3.4   
303   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     1       1  
303      1   1     2       0

In [66]:
#total rows and columns
heartds.shape

(304, 14)

In [67]:
heartds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 304 entries, 0 to 303
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       304 non-null    int64  
 1   sex       304 non-null    int64  
 2   cp        304 non-null    int64  
 3   trestbps  304 non-null    int64  
 4   chol      304 non-null    int64  
 5   fbs       304 non-null    int64  
 6   restecg   304 non-null    int64  
 7   thalach   304 non-null    int64  
 8   exang     304 non-null    int64  
 9   oldpeak   304 non-null    float64
 10  slope     304 non-null    int64  
 11  ca        304 non-null    int64  
 12  thal      304 non-null    int64  
 13  target    304 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.4 KB


In [68]:
heartds.groupby('target').size()

target
0    138
1    166
dtype: int64

In [69]:
heartds['target'].value_counts()
#the above step and this step both are used to check a column's distribution

1    166
0    138
Name: target, dtype: int64

In [70]:
heartds['age'].value_counts()

58    19
57    17
54    16
59    14
51    13
52    13
62    11
60    11
44    11
56    11
64    10
41    10
63     9
67     9
65     8
43     8
45     8
55     8
42     8
61     8
53     8
46     7
48     7
66     7
50     7
49     5
47     5
70     4
39     4
35     4
68     4
38     3
71     3
40     3
69     3
34     2
37     2
29     1
74     1
76     1
77     1
Name: age, dtype: int64

In [71]:
#total size of the dataset
heartds.size


4256

In [72]:
#statistics of our dataset
heartds.describe()

age         sex          cp    trestbps        chol         fbs  \
count  304.000000  304.000000  304.000000  304.000000  304.000000  304.000000   
mean    54.355263    0.684211    0.963816  131.664474  246.322368    0.148026   
std      9.069157    0.465596    1.031840   17.523560   51.755149    0.355712   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     47.750000    0.000000    0.000000  120.000000  211.000000    0.000000   
50%     55.000000    1.000000    1.000000  130.000000  240.500000    0.000000   
75%     61.000000    1.000000    2.000000  140.000000  274.250000    0.000000   
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  304.000000  304.000000  304.000000  304.000000  304.000000  304.000000   
mean     0.529605  149.618421    0.328947    1.047368    1.398026    0.730263   
std      0.525688   22.872710    0.470605    1.167036    0.615635    1.021035   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.750000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  152.500000    0.000000    0.800000    1.000000    0.000000   
75%      1.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    4.000000   

             thal      target  
count  304.000000  304.000000  
mean     2.309211    0.546053  
std      0.615890    0.498696  
min      0.000000    0.000000  
25%      2.000000    0.000000  
50%      2.000000    1.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

In [73]:
#check for null values
heartds.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [74]:
#There are no null values in our dataset

In [75]:
#Data Visualization


In [127]:
#Train_Test_split
#into X_train,X_test,Y_train,Y_train
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [128]:
sc = StandardScaler()
X = sc.fit_transform(X)

In [129]:
Y

0      1
1      1
2      1
3      1
4      1
      ..
299    0
300    0
301    0
302    1
303    0
Name: target, Length: 304, dtype: int64

In [130]:
X

array([[ 0.95477345,  0.67936622,  1.97660708, ..., -2.27461441,
        -0.71639745, -2.12922532],
       [-1.91681306,  0.67936622,  1.00586629, ..., -2.27461441,
        -0.71639745, -0.50288236],
       [-1.47503052, -1.47196014,  0.03512549, ...,  0.9794222 ,
        -0.71639745, -0.50288236],
       ...,
       [ 0.29209964,  0.67936622, -0.93561531, ..., -0.6475961 ,
         0.26461528,  1.1234606 ],
       [-0.37057417,  0.67936622, -0.93561531, ..., -0.6475961 ,
         0.26461528, -2.12922532],
       [ 0.29209964, -1.47196014,  0.03512549, ..., -0.6475961 ,
         0.26461528, -0.50288236]])

In [131]:
#Splitting into train and test data
X_train , X_test , Y_train , Y_test = train_test_split(X,Y,random_state=10,test_size=0.3,shuffle=True)
#Using random state data is split randomly

In [132]:
X_train

array([[-0.70191107,  0.67936622,  0.03512549, ..., -2.27461441,
        -0.71639745,  1.1234606 ],
       [ 0.40254527,  0.67936622, -0.93561531, ...,  0.9794222 ,
        -0.71639745,  1.1234606 ],
       [-2.24814996,  0.67936622,  1.97660708, ...,  0.9794222 ,
        -0.71639745, -0.50288236],
       ...,
       [-0.4810198 , -1.47196014,  1.00586629, ..., -0.6475961 ,
        -0.71639745, -0.50288236],
       [-2.24814996, -1.47196014,  0.03512549, ...,  0.9794222 ,
        -0.71639745, -0.50288236],
       [ 1.28611035,  0.67936622, -0.93561531, ...,  0.9794222 ,
         0.26461528, -0.50288236]])

In [133]:
Y_train

171    0
202    0
58     1
154    1
75     1
      ..
156    1
123    1
15     1
125    1
265    0
Name: target, Length: 212, dtype: int64

In [134]:
X_test

array([[ 0.51299091,  0.67936622, -0.93561531, ..., -0.6475961 ,
         0.26461528,  1.1234606 ],
       [ 0.40254527,  0.67936622,  1.00586629, ..., -0.6475961 ,
         0.26461528,  1.1234606 ],
       [-0.81235671,  0.67936622,  1.00586629, ...,  0.9794222 ,
        -0.71639745, -0.50288236],
       ...,
       [-0.26012853,  0.67936622,  0.03512549, ...,  0.9794222 ,
        -0.71639745, -0.50288236],
       [ 0.62343654,  0.67936622, -0.93561531, ..., -0.6475961 ,
         1.245628  ,  1.1234606 ],
       [-0.1496829 , -1.47196014, -0.93561531, ...,  0.9794222 ,
        -0.71639745, -0.50288236]])

In [135]:
Y_test

206    0
183    0
230    0
126    1
184    0
      ..
21     1
211    0
78     1
174    0
49     1
Name: target, Length: 92, dtype: int64

In [136]:
#Checking the shape of train and test data
X.shape, X_train.shape, X_test.shape

((304, 13), (212, 13), (92, 13))

In [137]:
Y.shape, Y_train.shape, Y_test.shape

((304,), (212,), (92,))

In [138]:
scores_dict={}

In [200]:
Catagory=['No....but i pray you get Heart Disease or at leaset Corona Virus Soon...','Yes you have Heart Disease....RIP in Advance']

In [139]:
#MODEL TRAINING
#USING LOGISTIC REGRESSION

In [147]:
#we are going to use logistic regression
mymodel = DecisionTreeClassifier()

In [148]:
#training our model with train data

In [149]:
mymodel.fit(X_train, Y_train)

DecisionTreeClassifier()

In [150]:
#evaluationg our model 

In [151]:
X_train

array([[-0.70191107,  0.67936622,  0.03512549, ..., -2.27461441,
        -0.71639745,  1.1234606 ],
       [ 0.40254527,  0.67936622, -0.93561531, ...,  0.9794222 ,
        -0.71639745,  1.1234606 ],
       [-2.24814996,  0.67936622,  1.97660708, ...,  0.9794222 ,
        -0.71639745, -0.50288236],
       ...,
       [-0.4810198 , -1.47196014,  1.00586629, ..., -0.6475961 ,
        -0.71639745, -0.50288236],
       [-2.24814996, -1.47196014,  0.03512549, ...,  0.9794222 ,
        -0.71639745, -0.50288236],
       [ 1.28611035,  0.67936622, -0.93561531, ...,  0.9794222 ,
         0.26461528, -0.50288236]])

In [154]:
predicting_output = mymodel.predict(X_test)
accuracy_fit=accuracy_score(Y_test,predicting_output)*100

In [158]:
scores_dict['DecisionTreeClassifier'] = accuracy_fit
print('Accuracy : ',accuracy_fit)

Accuracy :  80.43478260869566


In [160]:
print("Accuracy on training set: {:.3f}".format(mymodel.score(X_train, Y_train)))


Accuracy on training set: 1.000


In [161]:
print("Accuracy on test set: {:.3f}".format(mymodel.score(X_test, Y_test)))

Accuracy on test set: 0.804


In [162]:
predicting_output

array([0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1])

In [201]:
X_DT=np.array([[63 ,1, 3,145,233,1,0,150,0,2.3,0,0,1]])
X_DT_predicting_output=mymodel.predict(X_DT)

In [211]:
X_DT_predicting_output[0]

print(Catagory[int(X_DT_predicting_output[0])])

Yes you have Heart Disease....RIP in Advance
